export const TiposExtensao = [
  {
    tipo: "Projeto de Extensão",
    aproveitamento: 0.1,
    limite: 40,
    limitePorAtividade: false,
    requisitos: ["Atestado e relatorio sobre as atividades desenvolvidas"],
  },
  {
    tipo: "Atividades culturais",
    aproveitamento: 0.05,
    limite: 20,
    limitePorAtividade: false,
    requisitos: ["Atestado e relatorio sobre as atividades desenvolvidas"],
  },
  {
    tipo: "Visitas Técnicas",
    aproveitamento: 1,
    limite: 40,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Visitas a Feiras e Exposições",
    aproveitamento: 0.2,
    limite: 5,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Cursos de Idiomas",
    aproveitamento: 0.6,
    limite: 20,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Palestras, Seminários e Congressos Extensionistas (ouvinte)",
    aproveitamento: 0.8,
    limite: 10,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Palestras, Seminários e Congressos Extensionistas (apresentador)",
    aproveitamento: 1,
    limite: 15,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Projeto Empresa Júnior",
    aproveitamento: 0.2,
    limite: 20,
    limitePorAtividade: false,
    requisitos: [],
  },
];

export const TiposEnsino = [
  {
    tipo: "Estágio extracurricular",
    aproveitamento: 0.7,
    limite: 40,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Monitoria",
    aproveitamento: 0.7,
    limite: 40,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Concursos e campeonatos de atividades acadêmicas",
    aproveitamento: 0.7,
    limite: 50,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Presença comprovada a defesas de TCC do curso de Engenharia da Computação",
    aproveitamento: 0.5,
    limite: 3,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Cursos Profissionalizantes específicos na área",
    aproveitamento: 0.8,
    limite: 40,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Cursos profissionalizantes em geral",
    aproveitamento: 0.2,
    limite: 10,
    limitePorAtividade: false,
    requisitos: [],
  },
];

export const TiposPesquisa = [
  {
    tipo: "Iniciação Científica",
    aproveitamento: 0.8,
    limite: 40,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Publicação de artigos em periódicos científicos",
    aproveitamento: 1,
    limite: 10,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Publicação de artigos comppletos em anais de congressos",
    aproveitamento: 1,
    limite: 0.7,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Publicação de capítulo de livro",
    aproveitamento: 1,
    limite: 0.7,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Publicação de resumos de artigos em anais",
    aproveitamento: 1,
    limite: 0.7,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Registro de patentes como auto/coautor",
    aproveitamento: 1,
    limite: 40,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Premiação resultante de pesquisa científica",
    aproveitamento: 1,
    limite: 10,
    limitePorAtividade: true,
    requisitos: [],
  },
  {
    tipo: "Colaborador em atividades como Seminários e Congressos",
    aproveitamento: 1,
    limite: 10,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Palestras, Seminários e Congressos de pesquisa (ouvinte)",
    aproveitamento: 0.8,
    limite: 10,
    limitePorAtividade: false,
    requisitos: [],
  },
  {
    tipo: "Palestras, Seminários e Congressos de Pesquisa (ouvinte)",
    aproveitamento: 1,
    limite: 15,
    limitePorAtividade: false,
    requisitos: [],
  },
];
